os_user_name=root
db_user_name=root
v_commit=6111b6e
v_testdb=v2082rc4_0305_6111b6e
v_db_parent_dir=/data1/iotdb
v_cn_db_parent_dir=/data/iotdb
v_shell_client_db_parent_dir=/data2/iotdb
bm_ssl_dir=/data1/iotdb/bm_20251017_b6be9bd
bm_v13_dir=/data1/iotdb/bm_20251017_b6be9bd_v13
bm_conn_pw=TimechoDB@2021
root_pw=TimechoDB@2021
monitor_url=http://172.16.2.25:9090
CLUSTER_NAME=ClusterID1
test_result_iotdb_ip=172.16.2.31
