drop database db;
create database db;
use db;
create table t(device_id string tag,id int32);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
insert into t(time,device_id,id) values(now(),'d1',1);
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
delete from t;
flush;
