os_user_name=root
db_user_name=root
v_commit=2d2d5c9
v_testdb=v2092rc1_0423_12d2d5c9
v_db_parent_dir=/data/iotdb
v_cn_db_parent_dir=/data/iotdb
v_shell_client_db_parent_dir=/data/iotdb
bm_dir=/benchmark/bm_20260423_obj_6d3310ad_v20
bm_conn_pw=TimechoDB@2021
root_pw=TimechoDB@2021
bm1_ip=172.20.70.120
bm2_ip=172.20.70.121
monitor_url=http://172.20.70.122:9090
CLUSTER_NAME=weather
test_result_iotdb_ip=172.20.70.122
